### ISSUE TITLE
Issue trying this code

### ISSUE THREAD

**Issue by analog-io** [WarrenWeckesser/eyediagram#1]
This looks like a very useful tool!  I tried to download and run the demo, here was my process:

1) Download zip and extract
2) run "python setup.py build"
3) move demo_mpl.py to the folder one level above the "eyediagram" folder
4) run demo_mpl.py in python

The result is the following error messages:

Traceback (most recent call last):
  File "mpl_demo.py", line 5, in <module>
    from eyediagram.mpl import eyediagram
  File "/Users/lgbeno/Downloads/eyediagram-master/eyediagram/mpl.py", line 7, in <module>
    from .core import grid_count as _grid_count
  File "/Users/lgbeno/Downloads/eyediagram-master/eyediagram/core.py", line 8, in <module>
    from .brescount import bres_curve_count as _bres_curve_count
ImportError: No module named brescount
Lukes-MacBook-Pro:eyediagram-master lgbeno$ python mpl_demo.py 
Traceback (most recent call last):
  File "mpl_demo.py", line 5, in <module>
    from eyediagram.mpl import eyediagram
  File "/Users/lgbeno/Downloads/eyediagram-master/eyediagram/mpl.py", line 7, in <module>
    from .core import grid_count as _grid_count
  File "/Users/lgbeno/Downloads/eyediagram-master/eyediagram/core.py", line 8, in <module>
    from ._brescount import bres_curve_count as _bres_curve_count
ImportError: No module named _brescount

I verified that brescount.pyx is in the eyediagram folder, I also tried changing the import to:
from .brescount import bres_curve_count as _bres_curve_count

(removed the _ in front of brescount)

any suggestions?

**Comment by WarrenWeckesser** [comment]
Do you have cython installed?  Did you get any errors or warnings when you ran `python setup.py build`?  Have you tried `python setup.py install`?

**Comment by analog-io** [comment]
Yes I believe that cython is installed, I also tried python setup.py install (which I had not done before) however, still experiencing the same issue.

Lukes-MacBook-Pro:eyediagram-master lgbeno$ cython -V
Cython version 0.22.1
Lukes-MacBook-Pro:eyediagram-master lgbeno$ python -V
Python 2.7.10 :: Anaconda 2.3.0 (x86_64)

Here is a zip of my actual directory. https://www.dropbox.com/s/5hpmok9c38ekix7/eyediagram-master%202.zip?dl=0

**Comment by WarrenWeckesser** [comment]
I am also using Anaconda on a Macbook.  I just went through what I believe is a fairly standard installation procedure, and it worked:

```
$ unzip eyediagram-0.1.0.zip 
$ cd eyediagram-0.1.0
$ python setup.py install
$ cd demo/
$ python mpl_demo.py
```

If you use that method, then to uninstall an old installation, you would go to `$HOME/anaconda/lib/python2.7/site-packages`, and `rm -rf eyediagram*`.

Perhaps a better installation procedure is to use `pip`:

```
$ unzip eyediagram-0.1.0.zip 
$ cd eyediagram-0.1.0
$ pip install .
```

Then the same steps to run the demo should work:

```
$ cd demo/
$ python mpl_demo.py
```

By using `pip`, you can uninstall the package with the command

```
$ pip uninstall eyediagram
```

**Comment by analog-io** [comment]
Hi Warren,

Thank you for the help,  following your instructions, I was able to get the demo to work.

Thanks again!

**Comment by WarrenWeckesser** [comment]
Great!  Thanks for giving `eyediagram` a shot.
