### ISSUE TITLE
No module in the list could be found

### ISSUE THREAD

**Issue by houmingc** [WarrenWeckesser/eyediagram#3]
I am trying to plot eye diagram using matplotlib. After unzip to run the demo code, i found several errors listed below. Searching the downloaded folder, could not find this two module. Please kindly assist.

ImportError: No module named eyediagram.demo_data
ImportError: No module named eyediagram.mpl

**Comment by WarrenWeckesser** [comment]
To install the package, it is not sufficient to simply unzip the zip file.  You have to install it using one of the standard python installation procedures.  According to https://packaging.python.org/installing/, `pip` is the recommended method.  The following should work:

    pip install eyediagram-0.1.0.zip 

Before you run that, check that you have cython, numpy and scipy already installed.  They are required by the eyediagram package.

**Comment by houmingc** [comment]
[ERROR] Sorry! ionic serve can only be run in an Ionic project directory when run ionic serve
