### ISSUE TITLE
How to plot eye diagram from a time-domain signal of csv file?

### ISSUE THREAD

**Issue by piashdas** [WarrenWeckesser/eyediagram#4]
Hello,
I liked your explanation. I have a time-domain signal generated from Cadence Virtuoso at the receiver side. I can plot eye diagram in Virtuoso. But I am having the problem to generate eye diagram from the signal. 

The total time signal is 30ns total and I used 500ps as the period for generating eye diagram in Virtuoso. In the exported CSV file, the 1st column contains the time and 2nd column contains values in real numbers of voltage. I cannot getting the idea how to sample it and then how to superimpose the sampled vector of voltage. Can you help me?

**Comment by WarrenWeckesser** [comment]
This is an old issue, so I'm closing it as it is probably no longer of interest.  (I had stopped developing `eyediagram` for quite a few years, and didn't have time for support.)
