### ISSUE TITLE
Compatibility with matplotlib >= 2.0.0

### ISSUE THREAD

**Issue by martinfiers** [WarrenWeckesser/eyediagram#6]
Since matplotlib version 2.0, set_axis_bgcolor has been deprecated in favor of set_facecolor.

(see According to https://matplotlib.org/2.1.2/api/_as_gen/matplotlib.axes.Axes.set_axis_bgcolor.html, ).

I usually use distutils.version.LooseVersion to do a comparison of version numbers. Not sure if there's a better way to do this?

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the issue.  I'll take a look, but probably not until January.

**Comment by WarrenWeckesser** [comment]
After years of neglect, I updated the matplotlib code, so I'm closing this.
