### ISSUE TITLE
How to contact?

### ISSUE THREAD

**Issue by ncboomin** [WarrenWeckesser/eyediagram#8]
Hi Warren, I've been trying to reach out to you to contact regarding some questions I have about your base code.

I am trying to implement it for a signal that I have for a research project.

Please let me know that best way to get in touch with you.

Best Regards,
Rohan Gulur

**Comment by WarrenWeckesser** [comment]
You can email me: warren.weckesser@gmail.com

I enabled my email address in my profile; we'll see if I end up regretting that.

**Comment by WarrenWeckesser** [comment]
If you have a question about the code in this repository, you can also ask it in an issue, if you don't mind the discussion being public.
